Feature/ac 24629 | AC Package - Add 'Resolution' picklist to events | AC package 1.5
advisors-excel-llc/ac-metadata-instructions pull request #75
Opened 2023-07-31 03:15 UTC by AmarenderN

Depends on [224](https://github.com/advisors-excel-llc/sf-ac/pull/224)

2023-08-29 23:05 UTC, jduclos-ae requested changes
Will test section a once the other PR is ready, aside from the few typos, looks like the rest are running ok.

2023-08-29 23:20 UTC, AmarenderN commented on 1.5.1
> +                    "actionTypeName": "command__Meeting_Outcomer__c",
This is Not ready forgot to  remove "Ready" the label, as it is depends on the rank related work.I will push updated instruction here with the working one

2023-08-29 23:29 UTC, AmarenderN commented on 1.5.1
> +                    "actionTypeName": "command__Meeting_Outcomer__c",
Corrected the API Name,But we can test this after the rank related sf-ac pr

2023-08-29 23:29 UTC, AmarenderN commented on 1.5.1
> +                    "actionTypeName": "command__Meeting_Outcomer__c",
Corrected the API Name,

2023-09-14 18:29 UTC, jduclos-ae approved these changes

2023-09-15 14:04 UTC, merged