Feature/ac 1813 | instructions for adding matching rules to duplicate rule for the merge tool
advisors-excel-llc/ac-metadata-instructions pull request #84
Opened 2023-08-21 21:54 UTC by KilMad

2023-08-23 04:22 UTC, AmarenderN approved these changes
Instructions are working .And AC-20076 instruction already in the "develop" branch

2023-09-27 16:55 UTC, jduclos-ae requested changes

2023-09-27 16:55 UTC, jduclos-ae commented on 1.5.0
> +                 "jiraTicket": "AC-37821",
add letter

2023-09-27 16:55 UTC, jduclos-ae commented on 1.5.0
> +                 "jiraTicket": "AC-37821",
add letter

2023-09-28 21:42 UTC, jduclos-ae approved these changes

2023-09-28 21:43 UTC, merged